# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'foodwhim' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for foodwhim
  pod 'YelpAPI'

  target 'foodwhimTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'foodwhimUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
